default['java']['jdk_version']='7'
default['sudo_elastic']['home_path']='/home/vagrant'
default['sudo_elastic']['elastic_search']['network_host']='0.0.0.0'
default['sudo_elastic']['ik']['version']='1.8.0'
default['sudo_elastic']['elastic_search']['cluster']['name']='my_escluster'
default['sudo_elastic']['elastic_search']['node']['name']='node1'
